//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Archpack.Training.ServiceUnits.Shared.V1.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringContents {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringContents() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Archpack.Training.ServiceUnits.Shared.V1.Resources.StringContents", typeof(StringContents).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   達成数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AchieveCount {
            get {
                return ResourceManager.GetString("AchieveCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   達成率 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AchieveRate {
            get {
                return ResourceManager.GetString("AchieveRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アクション に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実績工数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ActualManHour {
            get {
                return ResourceManager.GetString("ActualManHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新規登録 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddItem {
            get {
                return ResourceManager.GetString("AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   基本情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Basic {
            get {
                return ResourceManager.GetString("Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   請求書.xls に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BillingFileName {
            get {
                return ResourceManager.GetString("BillingFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BillingTemplate.xls に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BillingTemplateFileName {
            get {
                return ResourceManager.GetString("BillingTemplateFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   部署 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BusinessUnit {
            get {
                return ResourceManager.GetString("BusinessUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取消 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CancelApplication {
            get {
                return ResourceManager.GetString("CancelApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カテゴリ名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変更 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   閉じる に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Colon {
            get {
                return ResourceManager.GetString("Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワードの確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   件を表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataCount {
            get {
                return ResourceManager.GetString("DataCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   件中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataTotalCount {
            get {
                return ResourceManager.GetString("DataTotalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   トップページ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DefaultPage {
            get {
                return ResourceManager.GetString("DefaultPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeleteItem {
            get {
                return ResourceManager.GetString("DeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   納品書.xls に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeliveryFileName {
            get {
                return ResourceManager.GetString("DeliveryFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DeliveryTemplate.xls に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeliveryTemplateFileName {
            get {
                return ResourceManager.GetString("DeliveryTemplateFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   説明 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   詳細 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   差分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DiffHours {
            get {
                return ResourceManager.GetString("DiffHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルダウンロードを開始しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DownloadStartMessage {
            get {
                return ResourceManager.GetString("DownloadStartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実施日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExecutionDate {
            get {
                return ResourceManager.GetString("ExecutionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルダウンロードが完了しましたら、この画面を閉じてください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FIleDownloadMessage {
            get {
                return ResourceManager.GetString("FIleDownloadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルダウンロードの準備を行っています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileDownloadTitle {
            get {
                return ResourceManager.GetString("FileDownloadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フリガナ（名） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FirstNamePhonetic {
            get {
                return ResourceManager.GetString("FirstNamePhonetic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サーバーで予期しないシステムエラーが発生しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InternalServerErrorMessage {
            get {
                return ResourceManager.GetString("InternalServerErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ホームへ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InternalServerErrorNavigationMessage {
            get {
                return ResourceManager.GetString("InternalServerErrorNavigationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   システムエラーが発生しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InternalServerErrorTitle {
            get {
                return ResourceManager.GetString("InternalServerErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   姓 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フリガナ（姓） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LastNamePhonetic {
            get {
                return ResourceManager.GetString("LastNamePhonetic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログイン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログアウト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   電子メール に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   管理 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   月 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   月間目標 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MonthlyGoal {
            get {
                return ResourceManager.GetString("MonthlyGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   翌々月末日払い に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NextMonthAfterPayment {
            get {
                return ResourceManager.GetString("NextMonthAfterPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   翌月末日払い に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NextMonthPayment {
            get {
                return ResourceManager.GetString("NextMonthPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   次を検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NextSearch {
            get {
                return ResourceManager.GetString("NextSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   いいえ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたページはありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotFoundErrorMessage {
            get {
                return ResourceManager.GetString("NotFoundErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自動的にページが切り替わらない場合にはこのリンクをクリックしてください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotFoundErrorNavigationMessage {
            get {
                return ResourceManager.GetString("NotFoundErrorNavigationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたページはありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotFoundErrorTitle {
            get {
                return ResourceManager.GetString("NotFoundErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   その他 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OtherPayment {
            get {
                return ResourceManager.GetString("OtherPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   担当者 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   予定工数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlanManHour {
            get {
                return ResourceManager.GetString("PlanManHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   予定タスク に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlanTask {
            get {
                return ResourceManager.GetString("PlanTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   予定週 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlanWeek {
            get {
                return ResourceManager.GetString("PlanWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   役職 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   案件管理 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProcessManagement {
            get {
                return ResourceManager.GetString("ProcessManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   案件検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProcessSearch {
            get {
                return ResourceManager.GetString("ProcessSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロファイル情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロジェクト名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワード変更 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロール所属ユーザー編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RoleHeaderDetail {
            get {
                return ResourceManager.GetString("RoleHeaderDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロール名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロール情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロール検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RoleSearchListInput {
            get {
                return ResourceManager.GetString("RoleSearchListInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロール所属ユーザー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RolesInUsers {
            get {
                return ResourceManager.GetString("RolesInUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ~/Apps/Sales/proto/FileTemplates に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SalesExcelTemplateUrl {
            get {
                return ResourceManager.GetString("SalesExcelTemplateUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索条件 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchCriteria {
            get {
                return ResourceManager.GetString("SearchCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   結果一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchResultList {
            get {
                return ResourceManager.GetString("SearchResultList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectItem {
            get {
                return ResourceManager.GetString("SelectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サービス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   候補者管理 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StaffManagement {
            get {
                return ResourceManager.GetString("StaffManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   候補者検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StaffSearch {
            get {
                return ResourceManager.GetString("StaffSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サブカテゴリ名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SubCategoryName {
            get {
                return ResourceManager.GetString("SubCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   システムエラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SystemError {
            get {
                return ResourceManager.GetString("SystemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   目標達成数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TargetAchieve {
            get {
                return ResourceManager.GetString("TargetAchieve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象月 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TargetMonth {
            get {
                return ResourceManager.GetString("TargetMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タスク名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TaskName {
            get {
                return ResourceManager.GetString("TaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   電話番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tel {
            get {
                return ResourceManager.GetString("Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   送付状.xls に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TransmittalFileName {
            get {
                return ResourceManager.GetString("TransmittalFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TransmittalTemplate.xls に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TransmittalTemplateFileName {
            get {
                return ResourceManager.GetString("TransmittalTemplateFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたページを利用する権限がありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnauthorizedErrorMessage {
            get {
                return ResourceManager.GetString("UnauthorizedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自動的にページが切り替わらない場合にはこのリンクをクリックしてください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnauthorizedErrorNavigationMessage {
            get {
                return ResourceManager.GetString("UnauthorizedErrorNavigationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ページを利用する権限がありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnauthorizedErrorTitle {
            get {
                return ResourceManager.GetString("UnauthorizedErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザー編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserInput {
            get {
                return ResourceManager.GetString("UserInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザー所属ロール に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserInRoles {
            get {
                return ResourceManager.GetString("UserInRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザー一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserList {
            get {
                return ResourceManager.GetString("UserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   所属ユーザー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザー名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザー情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザー検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserSearchList {
            get {
                return ResourceManager.GetString("UserSearchList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作業週 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作業目標 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WeeklyGoal {
            get {
                return ResourceManager.GetString("WeeklyGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作業実績 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WeeklyResult {
            get {
                return ResourceManager.GetString("WeeklyResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   年 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   はい に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
