//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Archpack.Training.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Archpack.Training.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {0}が不正です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ArgumentAssertMessage {
            get {
                return ResourceManager.GetString("ArgumentAssertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}に空文字を指定できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ArgumentIsEmptyMessageFormat {
            get {
                return ResourceManager.GetString("ArgumentIsEmptyMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}にnullを指定できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ArgumentPropertyNullMessageFormat {
            get {
                return ResourceManager.GetString("ArgumentPropertyNullMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   適切な権限のあるユーザーでログインしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AuthorizedErrorMessage {
            get {
                return ResourceManager.GetString("AuthorizedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定された SQL クエリの実行に失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DataQueryException {
            get {
                return ResourceManager.GetString("DataQueryException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定された SQL クエリは存在しません。{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DataQueryNotFoundExceptionMesage {
            get {
                return ResourceManager.GetString("DataQueryNotFoundExceptionMesage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データの保存に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DbSaveErrorMessage {
            get {
                return ResourceManager.GetString("DbSaveErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すでに他のユーザーがこのデータを変更しています。最新のデータを取得してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DbUpdateConcurrencyError {
            get {
                return ResourceManager.GetString("DbUpdateConcurrencyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   argument [{0}] is not defined in enum [{1}]. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidEnumValueMessageFormat {
            get {
                return ResourceManager.GetString("InvalidEnumValueMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたファイルコンテンツのサイズが{0}を超えているためダウンロードできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MaxSizeDownloadFile {
            get {
                return ResourceManager.GetString("MaxSizeDownloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アクションの登録がありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoActionRegister {
            get {
                return ResourceManager.GetString("NoActionRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このメソッドの実行はサポートされていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotImplemetedExcetpion {
            get {
                return ResourceManager.GetString("NotImplemetedExcetpion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログインユーザーに適切な権限がありません。 employeeCode:{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RoleAuthorizedErrorMessage {
            get {
                return ResourceManager.GetString("RoleAuthorizedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サービスでエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ServiceError {
            get {
                return ResourceManager.GetString("ServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}に{1}以外の型を指定することはできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SpecifyValueType {
            get {
                return ResourceManager.GetString("SpecifyValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   システムエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SystemErrorMessage {
            get {
                return ResourceManager.GetString("SystemErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   認証されていないユーザーのユーザー情報は取得できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UserNotAuthenticated {
            get {
                return ResourceManager.GetString("UserNotAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザー情報が登録されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UserNotExist {
            get {
                return ResourceManager.GetString("UserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたファイルコンテンツがありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZeroLengthDownloadFile {
            get {
                return ResourceManager.GetString("ZeroLengthDownloadFile", resourceCulture);
            }
        }
    }
}
