//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Archpack.Training.ArchUnits.WebApiModels.V1 {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Archpack.Training.ArchUnits.WebApiModels.V1.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   適切な権限のあるユーザーでログインしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AuthorizedErrorMessage {
            get {
                return ResourceManager.GetString("AuthorizedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データの保存に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DbSaveErrorMessage {
            get {
                return ResourceManager.GetString("DbSaveErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すでに他のユーザーがこのデータを変更しています。最新のデータを取得してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DbUpdateConcurrencyError {
            get {
                return ResourceManager.GetString("DbUpdateConcurrencyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログインユーザーに適切な権限がありません。  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RoleAuthorizedErrorMessage {
            get {
                return ResourceManager.GetString("RoleAuthorizedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サービスでエラーが発生しました。管理者に問い合わせてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ServiceError {
            get {
                return ResourceManager.GetString("ServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   システムエラーが発生しました。管理者に問い合わせてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SystemErrorMessage {
            get {
                return ResourceManager.GetString("SystemErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サービスで入力検証エラーが発生しました。管理者に問い合わせてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ValidationErrorMessage {
            get {
                return ResourceManager.GetString("ValidationErrorMessage", resourceCulture);
            }
        }
    }
}
