//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Archpack.Training.ServiceUnits.Trainings.V1.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Archpack.Training.ServiceUnits.Trainings.V1.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 権限エラー.
        /// </summary>
        public static string AuthorizedError {
            get {
                return ResourceManager.GetString("AuthorizedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 適切な権限のあるユーザーでログインしてください。.
        /// </summary>
        public static string AuthorizedErrorMessage {
            get {
                return ResourceManager.GetString("AuthorizedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ページにアクセスする権限がありません。.
        /// </summary>
        public static string AuthorizedErrorMessageTitle {
            get {
                return ResourceManager.GetString("AuthorizedErrorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 明細件数が上限を超えています。請求書を出力しますか？.
        /// </summary>
        public static string BillingDetailsCountOverMessage {
            get {
                return ResourceManager.GetString("BillingDetailsCountOverMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検索条件が変更されました。再検索してください。.
        /// </summary>
        public static string ChangeSearchCriteria {
            get {
                return ResourceManager.GetString("ChangeSearchCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 明細行を削除しますか？.
        /// </summary>
        public static string ConfirmDeleteDetail {
            get {
                return ResourceManager.GetString("ConfirmDeleteDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to すでに他のユーザーがこのデータを変更したために、最新のデータを再度取得しました。.
        /// </summary>
        public static string ConflictAndGetNew {
            get {
                return ResourceManager.GetString("ConflictAndGetNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アカウント登録完了のお知らせ.
        /// </summary>
        public static string CreateUserMailSubject {
            get {
                return ResourceManager.GetString("CreateUserMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アップロードでエラーが発生しています。
        ///アップロードしたファイルの下記のエラーを修正して再度アップロードしてください。.
        /// </summary>
        public static string CSVUploadError {
            get {
                return ResourceManager.GetString("CSVUploadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {name} は金額で入力してください。.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {name} は日付を入力してください。.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 削除処理が完了しました。.
        /// </summary>
        public static string DeleteComplete {
            get {
                return ResourceManager.GetString("DeleteComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {name} は数字のみで入力してください。.
        /// </summary>
        public static string Digits {
            get {
                return ResourceManager.GetString("Digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 複数のヘッダーの更新はできません。.
        /// </summary>
        public static string DisallowMultiHeaderUpdate {
            get {
                return ResourceManager.GetString("DisallowMultiHeaderUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は半角英数記号のみで入力して下さい。.
        /// </summary>
        public static string ErrorAlphaNumberSymbolFormat {
            get {
                return ResourceManager.GetString("ErrorAlphaNumberSymbolFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は{1}形式で入力してください。.
        /// </summary>
        public static string ErrorDateFormat {
            get {
                return ResourceManager.GetString("ErrorDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 桁数にマイナスは指定できません。.
        /// </summary>
        public static string ErrorDigitMinus {
            get {
                return ResourceManager.GetString("ErrorDigitMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は半角英数字のみで入力してください。.
        /// </summary>
        public static string ErrorHalfAlphaNumberFormat {
            get {
                return ResourceManager.GetString("ErrorHalfAlphaNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は半角文字で入力してください。.
        /// </summary>
        public static string ErrorHalfStringFormat {
            get {
                return ResourceManager.GetString("ErrorHalfStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}はメールアドレスを入力してください。.
        /// </summary>
        public static string ErrorMailAddressFormat {
            get {
                return ResourceManager.GetString("ErrorMailAddressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は{1}文字以下で入力してください。.
        /// </summary>
        public static string ErrorMaxLength {
            get {
                return ResourceManager.GetString("ErrorMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は{1}以下の値を入力してください。.
        /// </summary>
        public static string ErrorMaxValue {
            get {
                return ResourceManager.GetString("ErrorMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラーが発生しました。.
        /// </summary>
        public static string ErrorMessageTitle {
            get {
                return ResourceManager.GetString("ErrorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラーが発生しました。.
        /// </summary>
        public static string ErrorMessageTitle1 {
            get {
                return ResourceManager.GetString("ErrorMessageTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は{1}文字以上で入力してください。.
        /// </summary>
        public static string ErrorMinLength {
            get {
                return ResourceManager.GetString("ErrorMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は{1}以上の値を入力してください。.
        /// </summary>
        public static string ErrorMinValue {
            get {
                return ResourceManager.GetString("ErrorMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は数値で入力してください。.
        /// </summary>
        public static string ErrorNumberFormat {
            get {
                return ResourceManager.GetString("ErrorNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は必須入力です。.
        /// </summary>
        public static string ErrorRequired {
            get {
                return ResourceManager.GetString("ErrorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は全角文字で入力してください。.
        /// </summary>
        public static string ErrorWideStringFormat {
            get {
                return ResourceManager.GetString("ErrorWideStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 内容が変更されています、終了しますか？.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データアップロードに失敗しました。.
        /// </summary>
        public static string FailUpload {
            get {
                return ResourceManager.GetString("FailUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}を{1}に保存しました。.
        /// </summary>
        public static string FileSaveMessage {
            get {
                return ResourceManager.GetString("FileSaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルサイズが{0}MB以上です。.
        /// </summary>
        public static string FileSizeErrorMessage {
            get {
                return ResourceManager.GetString("FileSizeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {name} は半角英数記号を入力してください。.
        /// </summary>
        public static string HanEisuKigo {
            get {
                return ResourceManager.GetString("HanEisuKigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {name} は半角を入力してください。.
        /// </summary>
        public static string Hankaku {
            get {
                return ResourceManager.GetString("Hankaku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {name} は整数値のみで入力してください。.
        /// </summary>
        public static string Integer {
            get {
                return ResourceManager.GetString("Integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 列数が不正です。.
        /// </summary>
        public static string InvalidColumnSizeTextFieldFile {
            get {
                return ResourceManager.GetString("InvalidColumnSizeTextFieldFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ユーザー名もしくはパスワードが正しくありません。.
        /// </summary>
        public static string InvalidUserNameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUserNameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {name} は {param} 以下で入力してください。.
        /// </summary>
        public static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {name} は {param} 文字以内で入力してください。.
        /// </summary>
        public static string MaxByteLength {
            get {
                return ResourceManager.GetString("MaxByteLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {name} は {param} 文字以内で入力してください。.
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {name} は {param} 以上で入力してください。.
        /// </summary>
        public static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {name} は {param} 文字以上で入力してください。.
        /// </summary>
        public static string MinByteLength {
            get {
                return ResourceManager.GetString("MinByteLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {name} は {param} 文字以上で入力してください。.
        /// </summary>
        public static string MinLength {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データがありません。.
        /// </summary>
        public static string NoDataExsists {
            get {
                return ResourceManager.GetString("NoDataExsists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 明細行が存在しません。明細行を追加してください。.
        /// </summary>
        public static string NoDetailLine {
            get {
                return ResourceManager.GetString("NoDetailLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データがありません。.
        /// </summary>
        public static string NoFileDataMessage {
            get {
                return ResourceManager.GetString("NoFileDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ユーザーマスタに該当するデータが1件もありませんでした。.
        /// </summary>
        public static string NotEixistsUser {
            get {
                return ResourceManager.GetString("NotEixistsUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入力されたパスワードが一致しません。.
        /// </summary>
        public static string NotEqualPassword {
            get {
                return ResourceManager.GetString("NotEqualPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルをアップロードしてください。.
        /// </summary>
        public static string NotFoundUploadFile {
            get {
                return ResourceManager.GetString("NotFoundUploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nullは許可されません。.
        /// </summary>
        public static string NotNullError {
            get {
                return ResourceManager.GetString("NotNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {name} は数値のみで入力してください。.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 値が範囲を超えています。{0} から {1} までの数値を設定してください。.
        /// </summary>
        public static string OutOfRangeTextField {
            get {
                return ResourceManager.GetString("OutOfRangeTextField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最大表示可能件数を超えました。検索条件を絞って再検索してください。.
        /// </summary>
        public static string OverDisplayCount {
            get {
                return ResourceManager.GetString("OverDisplayCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {name} は {param[0]} から {param[1]} の範囲で入力してください。.
        /// </summary>
        public static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {name} は {param[0]} 文字以上 {param[1]} 文字以内で入力してください。.
        /// </summary>
        public static string RangeLength {
            get {
                return ResourceManager.GetString("RangeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 削除処理が完了しました。.
        /// </summary>
        public static string RemoveComplete {
            get {
                return ResourceManager.GetString("RemoveComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {name} は入力必須です。.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 必須の項目です。.
        /// </summary>
        public static string RequiredTextField {
            get {
                return ResourceManager.GetString("RequiredTextField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存処理が完了しました。.
        /// </summary>
        public static string SaveComplete {
            get {
                return ResourceManager.GetString("SaveComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サービスでエラーが発生しました。.
        /// </summary>
        public static string ServiceError {
            get {
                return ResourceManager.GetString("ServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワードを変更しました。.
        /// </summary>
        public static string SuccessChangePassword {
            get {
                return ResourceManager.GetString("SuccessChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データアップロードに成功しました。.
        /// </summary>
        public static string SuccessUpload {
            get {
                return ResourceManager.GetString("SuccessUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {name} は電話番号を入力してください（例:012-345-6789）。.
        /// </summary>
        public static string TelNum {
            get {
                return ResourceManager.GetString("TelNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不明なエラーが発生しました。.
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {name} は全角を入力してください。.
        /// </summary>
        public static string Zenkaku {
            get {
                return ResourceManager.GetString("Zenkaku", resourceCulture);
            }
        }
    }
}
